[build]
  base = "PresupuestoWeb"
  publish = "PresupuestoWeb"
  functions = "PresupuestoWeb/netlify/functions"

[build.environment]
  NETLIFY_BUILD_IMAGE = "jammy"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200



