[build]
  publish = "PresupuestoWeb"
  functions = "Netlify/functions"

[build.environment]
  NETLIFY_BUILD_IMAGE = "jammy"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


